replace process.stdout.clearLine by readline.cursorTo
hallh/elasticsearch-primary-balancer pull request #10
Opened 2020-12-14 14:56 UTC by heiderich

This fixes #9. It is inspired by https://stackoverflow.com/questions/34570452/node-js-stdout-clearline-and-cursorto-functions.

2020-12-15 20:55 UTC, hallh requested changes
Hi @heiderich, thanks for taking the time to fill in some blanks on this project, it's much appreciated!

About your solution. Moving the cursor position does not exactly replace the behaviour of `clearLine()`. Instead, it will just allow us to print from the beginning of the line. It won't delete the line's content, like the latter would.

This change will result in some weird behaviour when running this tool in a shell, potentially causing new output to partially overwrite previous output.

I checked the link you included and the actual issue here is that: when the tool is run in non-interactively (non-TTY), the `clearLine()` call will crash the program. With that in mind, I'd choose to keep the current behaviour when run with a TTY, and then choose the less predictable output when run in a non-TTY context. Like when it's run in Jenkins.

Node provides an [easy way to check for a TTY](https://nodejs.org/api/tty.html#apicontent), using the `process.stdout.isTTY` property. If the `clearLine()` calls are wrapped in a check for a TTY, the problem should be solved without any side-effects.

2020-12-18 10:32 UTC, heiderich commented
Thanks for your review, @hallh. I completely agree with your proposition and implemented it in c584586.

2020-12-18 22:23 UTC, hallh approved these changes

2020-12-18 22:23 UTC, hallh commented
Works great, thanks!

2020-12-18 22:23 UTC, merged