add docker setup
hallh/elasticsearch-primary-balancer pull request #8
Opened 2020-12-14 14:35 UTC by heiderich

2020-12-15 21:03 UTC, hallh requested changes
I've one request regarding the docker run command, but otherwise looking great. Thanks for contributing this!

2020-12-15 21:03 UTC, hallh commented on README.md
> +docker run --rm elasticsearch-primary-balancer:latest <options>
Due to the issue you found in #9, this command will fail with the `clearLine()` crash. If you change the run command to `docker run -it ...` then docker will run it interactivaly and assign a pseudo-TTY that prevents the crash.

Besides that, I generally prefer to include the `-it` flags for running dockers manually as it also gives you the option to interrupt the execution with Ctrl-C, so include that, and the PR is golden.

2020-12-18 10:38 UTC, heiderich commented on README.md
> +docker run --rm elasticsearch-primary-balancer:latest <options>
I generally also use `-it`, but forgot to add it here. I added it in 50956a9. With c584586 both versions should work.

2020-12-18 21:51 UTC, hallh approved these changes

2020-12-18 21:52 UTC, hallh commented
Good stuff, merging this 😎

2020-12-18 21:52 UTC, merged